// ─────────────────────────────────────────────────────────────────────────────
// F1 24 CAR OVERRIDES — Assetto Corsa Competizione PC
// Fuentes: F1 24 setup guides, community spreadsheets, in-game data.
// F1 24 tiene menos variación entre equipos que ACC entre GT3s,
// pero还是有细微差异 (wheelbase, downforce levels, tire compound sensitivity).
// ─────────────────────────────────────────────────────────────────────────────

const F1_CAR_OVERRIDES = {

    rb20: {
        name: 'Red Bull Racing RB20',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   12,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    sf24: {
        name: 'Ferrari SF-24',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    w15: {
        name: 'Mercedes-AMG W15',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    mcl38: {
        name: 'McLaren MCL38',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   12,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    amr24: {
        name: 'Aston Martin AMR24',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    a524: {
        name: 'Alpine A524',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    fw46: {
        name: 'Williams FW46',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    vcarb: {
        name: 'Visa Cash App RB VCARB 01',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   12,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    c44: {
        name: 'Stake F1 Team C44',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },

    vf24: {
        name: 'Haas VF-24',
        wingFrontMin: 1,  wingFrontMax: 6,   wingFrontStep: 1,
        wingRearMin:   1,  wingRearMax:   11,  wingRearStep: 1,
        diffOnMin: 50, diffOnMax: 95, diffOnStep: 1,
        diffOffMin: 20, diffOffMax: 70, diffOffStep: 1,
        camberFrontMin: -4.5, camberFrontMax: -2.0, camberStep: 0.05,
        camberRearMin:  -3.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.10, toeRearMax:  0.60,
        suspFrontMin: 1, suspFrontMax: 41, suspStep: 1,
        arbFrontMin: 1, arbFrontMax: 21, arbStep: 1,
        rideHeightFrontMin: 1, rideHeightFrontMax: 41, rideHeightStep: 1,
        brakeBiasMin: 52, brakeBiasMax: 60, brakeBiasStep: 0.1,
        tyrePressureMin: 19.5, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
    },
};

export function getF1CarOverride(carId) {
    return F1_CAR_OVERRIDES[carId] || null;
}
