// ─────────────────────────────────────────────────────────────────────────────
// CIRCUITS BY GAME
// Fuente: listados oficiales de cada juego + community wiki
// Formato: { id, name, class } — class = categoría de circuito para agrupar
// ─────────────────────────────────────────────────────────────────────────────

export const GAME_CIRCUITS = {

    // ── ASSETTO CORSA COMPETIZIONE ─────────────────────────────────────────
    acc: [
        { id: 'spa',              name: 'Circuit de Spa-Francorchamps',             class: 'Grand Prix' },
        { id: 'monza',            name: 'Autodromo Nazionale Monza',                class: 'Grand Prix' },
        { id: 'nurburgring',      name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'silverstone',      name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona',        name: 'Circuit de Barcelona-Catalunya',         class: 'Grand Prix' },
        { id: 'hungaroring',      name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'paul_ricard',      name: 'Circuit Paul Ricard',                    class: 'Grand Prix' },
        { id: 'zandvoort',       name: 'Circuit Zandvoort',                      class: 'Grand Prix' },
        { id: 'misano',           name: 'Misano World Circuit Marco Simoncelli',  class: 'Grand Prix' },
        { id: 'imola',            name: 'Autodromo Internazionale Enzo e Dino Ferrari', class: 'Grand Prix' },
        { id: 'brandshatch',      name: 'Brands Hatch Circuit',                  class: 'Grand Prix' },
        { id: 'donington',        name: 'Donington Park Racing Circuit',          class: 'Grand Prix' },
        { id: 'zolder',           name: 'Circuit Zolder',                         class: 'Grand Prix' },
        { id: 'lagunaseca',       name: 'WeatherTech Raceway Laguna Seca',      class: 'Grand Prix' },
        { id: 'sebring',          name: 'Sebring International Raceway',           class: 'Grand Prix' },
        { id: 'suzuka',           name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'bathurst',         name: 'Mount Panorama Circuit',                  class: 'Grand Prix' },
        { id: 'kyalami',         name: 'Kyalami Grand Prix Circuit',              class: 'Grand Prix' },
        { id: 'indianapolis',     name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'hockenheim',      name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'estoril',          name: 'Circuito do Estoril',                   class: 'Grand Prix' },
        { id: 'watkins_glen',     name: 'Watkins Glen International',           class: 'Grand Prix' },
        { id: 'zhuhai',          name: 'Zhuhai International Circuit',           class: 'Grand Prix' },
        { id: 'dubai',           name: 'Dubai Autodrome',                       class: 'Grand Prix' },
        { id: 'snetterton',       name: 'Snetterton Motor Racing Circuit',       class: 'Grand Prix' },
        { id: 'oultonpark',       name: 'Oulton Park Circuit',                   class: 'Grand Prix' },
        { id: 'mosport',          name: 'Canadian Tire Motorsport Park',          class: 'Grand Prix' },
        { id: 'salem',            name: 'Salem Circuit',                         class: 'Grand Prix' },
        { id: 'le_mans',          name: 'Circuit de la Sarthe',                  class: 'Endurance' },
        { id: 'gilles_villeneuve', name: 'Circuit Gilles Villeneuve',            class: 'Street Circuit' },
        { id: 'lasvegas',        name: 'Las Vegas Street Circuit',               class: 'Street Circuit' },
        { id: 'bahrain',          name: 'Bahrain International Circuit',         class: 'Grand Prix' },
    ],

    // ── iRacing ────────────────────────────────────────────────────────────
    iracing: [
        // ── OVAL (NASCAR, Indy) ─────────────────────────────────────────────
        { id: 'tracks_daytona_international_speedway', name: 'Daytona International Speedway', class: 'Oval' },
        { id: 'tracks_atlanta_motor_speedway', name: 'Atlanta Motor Speedway', class: 'Oval' },
        { id: 'tracks_bristol_motor_speedway', name: 'Bristol Motor Speedway', class: 'Oval' },
        { id: 'tracks_charlotte_motor_speedway', name: 'Charlotte Motor Speedway', class: 'Oval' },
        { id: 'tracks_dover_motor_speedway', name: 'Dover Motor Speedway', class: 'Oval' },
        { id: 'tracks_las_vegas_motor_speedway', name: 'Las Vegas Motor Speedway', class: 'Oval' },
        { id: 'tracks_martinsville_speedway', name: 'Martinsville Speedway', class: 'Oval' },
        { id: 'tracks_michigan_international_speedway', name: 'Michigan International Speedway', class: 'Oval' },
        { id: 'tracks_nashville_superspeedway', name: 'Nashville Superspeedway', class: 'Oval' },
        { id: 'tracks_new_hampshire_motor_speedway', name: 'New Hampshire Motor Speedway', class: 'Oval' },
        { id: 'tracks_phoenix_raceway', name: 'Phoenix Raceway', class: 'Oval' },
        { id: 'tracks_richmond_raceway', name: 'Richmond Raceway', class: 'Oval' },
        { id: 'tracks_talladega_superspeedway', name: 'Talladega Superspeedway', class: 'Oval' },
        { id: 'tracks_texas_motor_speedway', name: 'Texas Motor Speedway', class: 'Oval' },
        { id: 'tracks_kansas_speedway', name: 'Kansas Speedway', class: 'Oval' },
        { id: 'tracks_south_boston_speedway', name: 'South Boston Speedway', class: 'Oval' },
        { id: 'tracks_darlington_raceway', name: 'Darlington Raceway', class: 'Oval' },
        { id: 'tracks_north_wilkesboro_speedway', name: 'North Wilkesboro Speedway', class: 'Oval' },
        { id: 'tracks_world_of_forgiveness_speedway', name: 'World of Forgiveness Speedway', class: 'Oval' },

        // ── ROAD COURSES ───────────────────────────────────────────────────
        { id: 'tracks_spa_francorchamps', name: 'Circuit de Spa-Francorchamps', class: 'Road Course' },
        { id: 'tracks_monza', name: 'Autodromo Nazionale Monza', class: 'Road Course' },
        { id: 'tracks_silverstone', name: 'Silverstone Circuit', class: 'Road Course' },
        { id: 'tracks_nurburgring_gp', name: 'Nurburgring GP', class: 'Road Course' },
        { id: 'tracks_nurburgring_endurance', name: 'Nurburgring 24h', class: 'Road Course' },
        { id: 'tracks_barcelona_catalunya', name: 'Circuit de Barcelona-Catalunya', class: 'Road Course' },
        { id: 'tracks_hockenheimring', name: 'Hockenheimring', class: 'Road Course' },
        { id: 'tracks_zandvoort', name: 'Circuit Zandvoort', class: 'Road Course' },
        { id: 'tracks_le_mans_bugatti', name: 'Circuit de la Sarthe (Bugatti)', class: 'Road Course' },
        { id: 'tracks_imola', name: 'Autodromo di Imola', class: 'Road Course' },
        { id: 'tracks_mugello', name: 'Autodromo del Mugello', class: 'Road Course' },
        { id: 'tracks_cota', name: 'Circuit of the Americas', class: 'Road Course' },
        { id: 'tracks_sebring', name: 'Sebring International Raceway', class: 'Road Course' },
        { id: 'tracks_virginia_international_raceway', name: 'Virginia International Raceway', class: 'Road Course' },
        { id: 'tracks_laguna_seca', name: 'WeatherTech Raceway Laguna Seca', class: 'Road Course' },
        { id: 'tracks_road_america', name: 'Road America', class: 'Road Course' },
        { id: 'tracks_watkins_glen_international', name: 'Watkins Glen International', class: 'Road Course' },
        { id: 'tracks_mid_ohio', name: 'Mid-Ohio Sports Car Course', class: 'Road Course' },
        { id: 'tracks_oregon_speedway', name: 'Oregon Speedway', class: 'Road Course' },
        { id: 'tracks_pirelli_world_challenge', name: 'Pirelli World Challenge', class: 'Road Course' },
        { id: 'tracks_charlotte_roval', name: 'Charlotte Motor Speedway Roval', class: 'Road Course' },
        { id: 'tracks_donington_park', name: 'Donington Park', class: 'Road Course' },
        { id: 'tracks_brands_hatch', name: 'Brands Hatch', class: 'Road Course' },
        { id: 'tracks_oulton_park', name: 'Oulton Park', class: 'Road Course' },
        { id: 'tracks_zolder', name: 'Circuit Zolder', class: 'Road Course' },
        { id: 'tracks_norisring', name: 'Norisring', class: 'Road Course' },
        { id: 'tracks_estoril', name: 'Estoril Circuit', class: 'Road Course' },
        { id: 'tracks_mont_tremblant', name: 'Circuit Mont-Tremblant', class: 'Road Course' },
        { id: 'tracks_summit_point', name: 'Summit Point Motorsports Park', class: 'Road Course' },
        { id: 'tracks_road_atlanta', name: 'Road Atlanta', class: 'Road Course' },
        { id: 'tracks_lime_rock_park', name: 'Lime Rock Park', class: 'Road Course' },
        { id: 'tracks_willow_springs', name: 'Willow Springs International Raceway', class: 'Road Course' },
        { id: 'tracks_thunderhill', name: 'Thunderhill Raceway', class: 'Road Course' },
        { id: 'tracks_nelson_road_course', name: 'Nelson Ledges Road Course', class: 'Road Course' },
        { id: 'tracks_watkins_glen_sprint', name: 'Watkins Glen (Sprint)', class: 'Road Course' },
        { id: 'tracks_bahrain_international', name: 'Bahrain International Circuit', class: 'Road Course' },
        { id: 'tracks_jeddah_corner', name: 'Jeddah Corniche Circuit', class: 'Road Course' },
        { id: 'tracks_albert_park', name: 'Albert Park Circuit', class: 'Road Course' },
        { id: 'tracks_baku_city_circuit', name: 'Baku City Circuit', class: 'Road Course' },
        { id: 'tracks_miami_international', name: 'Miami International Autodrome', class: 'Road Course' },
        { id: 'tracks_monaco_circuit', name: 'Circuit de Monaco', class: 'Road Course' },
        { id: 'tracks_villeneuve_circuit', name: 'Circuit Gilles Villeneuve', class: 'Road Course' },
        { id: 'tracks_red_bull_ring', name: 'Red Bull Ring', class: 'Road Course' },
        { id: 'tracks_paul_ricard', name: 'Circuit Paul Ricard', class: 'Road Course' },
        { id: 'tracks_hungaroring', name: 'Hungaroring', class: 'Road Course' },
        { id: 'tracks_singapore_marina_bay', name: 'Marina Bay Street Circuit', class: 'Road Course' },
        { id: 'tracks_losail_international', name: 'Losail International Circuit', class: 'Road Course' },
        { id: 'tracks_suzuka_international', name: 'Suzuka International Racing Course', class: 'Road Course' },
        { id: 'tracks_mexico_city', name: 'Autodromo Hermanos Rodriguez', class: 'Road Course' },
        { id: 'tracks_interlagos', name: 'Autodromo Jose Carlos Pace', class: 'Road Course' },
        { id: 'tracks_las_vegas_street', name: 'Las Vegas Street Circuit', class: 'Road Course' },
        { id: 'tracks_abu_dhabi_yas_marina', name: 'Yas Marina Circuit', class: 'Road Course' },
        { id: 'tracks_sonoma_raceway', name: 'Sonoma Raceway', class: 'Road Course' },
        { id: 'tracks_zandvoort_dtm', name: 'Zandvoort (DTM)', class: 'Road Course' },

        // ── DIRT OVAL ───────────────────────────────────────────────────────
        { id: 'tracks_lane_motorsport', name: 'Lane Motorsport', class: 'Dirt Oval' },
        { id: 'tracks_ludington_speedway', name: 'Ludington Speedway', class: 'Dirt Oval' },
        { id: 'tracks_knoxville_raceway', name: 'Knoxville Raceway', class: 'Dirt Oval' },
        { id: 'tracks_bedford_speeedway', name: 'Bedford Speedway', class: 'Dirt Oval' },
        { id: 'tracks_hagerstown_speedway', name: 'Hagerstown Speedway', class: 'Dirt Oval' },
        { id: 'tracks_volusia_speedway', name: 'Volusia Speedway', class: 'Dirt Oval' },
        { id: 'tracks_i55_raceway', name: 'I-55 Raceway', class: 'Dirt Oval' },
        { id: 'tracks_south_boston_dirt', name: 'South Boston Speedway (Dirt)', class: 'Dirt Oval' },
        { id: 'tracks_fayetteville_motor_speedway', name: 'Fayetteville Motor Speedway', class: 'Dirt Oval' },
        { id: 'tracks_darlington_dirt', name: 'Darlington Raceway (Dirt)', class: 'Dirt Oval' },

        // ── RALLYCROSS ─────────────────────────────────────────────────────
        { id: 'tracks_hockenheim_rx', name: 'Hockenheim Rallycross', class: 'Rallycross' },
        { id: 'tracks_garda_rx', name: 'Lake Garda Rallycross', class: 'Rallycross' },
        { id: 'tracks_mona_co_rx', name: 'Monaco Rallycross', class: 'Rallycross' },
        { id: 'tracks_lontoy_rx', name: 'Lontoy Rallycross', class: 'Rallycross' },
        { id: 'tracks_chicago_rx', name: 'Chicago Rallycross', class: 'Rallycross' },
        { id: 'tracks_daytona_rx', name: 'Daytona Rallycross', class: 'Rallycross' },
        { id: 'tracks_silverstone_rx', name: 'Silverstone Rallycross', class: 'Rallycross' },
        { id: 'tracks_briarcliff_rx', name: 'Briarcliff Rallycross', class: 'Rallycross' },
    ],

    // ── GRAN TURISMO 7 ─────────────────────────────────────────────────────
    gt7: [
        { id: 'tokyo_expressway', name: 'Tokyo Expressway',                        class: 'Road Track' },
        { id: 'sardegna',        name: 'Sardegna - Road Track',                  class: 'Road Track' },
        { id: 'bluewaters_bay',   name: 'Bluewaters Bay',                         class: 'Road Track' },
        { id: 'alsace',          name: 'Alsace - Village',                       class: 'Road Track' },
        { id: 'bushido',         name: 'Blickwinkel',                           class: 'Road Track' },
        { id: 'deep_forest',     name: 'Deep Forest',                           class: 'Road Track' },
        { id: 'dragon_tail',     name: 'Dragon Trail',                          class: 'Road Track' },
        { id: 'willow_springs',  name: 'Willow Springs',                        class: 'Road Track' },
        { id: 'eagle_mountain',  name: 'Eagle Mountain',                        class: 'Road Track' },
        { id: 'fuji_speedway',   name: 'Fuji Speedway',                          class: 'Circuit Experience' },
        { id: 'autopolis',        name: 'Autopolis',                              class: 'Circuit Experience' },
        { id: 'suzuka_gt7',      name: 'Suzuka Circuit',                        class: 'Circuit Experience' },
        { id: 'nurburgring_gt7', name: 'Nürburgring',                           class: 'World Circuits' },
        { id: 'trial_mountain',   name: 'Trial Mountain Circuit',                class: 'Circuit Experience' },
        { id: 'laguna_seca_gt7', name: 'WeatherTech Raceway Laguna Seca',      class: 'World Circuits' },
        { id: 'homestead',       name: 'Homestead-Miami Speedway',               class: 'World Circuits' },
        { id: 'wellington',       name: 'Wellington Expressway',                  class: 'Street Circuit' },
        { id: 'sainte_croix',   name: 'Sainte-Croix',                          class: 'Road Track' },
        { id: 'gr1_cup',        name: 'Gr.1 Cup',                              class: 'Races' },
        { id: 'gr3_cup',        name: 'Gr.3 Cup',                              class: 'Races' },
    ],

    // ── F1 24 ──────────────────────────────────────────────────────────────
    f1_24: [
        { id: 'bahrain_f1',      name: 'Bahrain International Circuit',          class: 'Grand Prix' },
        { id: 'jeddah',          name: 'Jeddah Corniche Circuit',                 class: 'Street Circuit' },
        { id: 'albert_park',     name: 'Albert Park Grand Prix Circuit',         class: 'Street Circuit' },
        { id: 'suzuka_f1',      name: 'Suzuka International Racing Course',    class: 'Grand Prix' },
        { id: 'shanghai',        name: 'Shanghai International Circuit',          class: 'Grand Prix' },
        { id: 'miami',           name: 'Miami International Autodrome',          class: 'Street Circuit' },
        { id: 'catalunya_f1',   name: 'Circuit de Barcelona-Catalunya',           class: 'Grand Prix' },
        { id: 'monaco',          name: 'Circuit de Monaco',                      class: 'Street Circuit' },
        { id: 'gilles_villeneuve_f1', name: 'Circuit Gilles Villeneuve',          class: 'Street Circuit' },
        { id: 'silverstone_f1',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'red_bull_ring',   name: 'Red Bull Ring',                          class: 'Grand Prix' },
        { id: 'houston_street',  name: 'Heinz Field Street Circuit',             class: 'Street Circuit' },
        { id: 'zandvoort_f1',   name: 'Circuit Zandvoort',                      class: 'Grand Prix' },
        { id: 'monza_f1',        name: 'Autodromo Nazionale Monza',             class: 'Grand Prix' },
        { id: 'spa_f1',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'hungaroring_f1',  name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'zhou',           name: 'Zhuhai International Circuit',           class: 'Grand Prix' },
        { id: 'americas',        name: 'Circuit of the Americas',                class: 'Grand Prix' },
        { id: 'rodriguez',       name: 'Autodromo Hermanos Rodriguez',            class: 'Grand Prix' },
        { id: 'interlagos',      name: 'Autodromo Jose Carlos Pace',             class: 'Grand Prix' },
        { id: 'lasvegas_f1',    name: 'Las Vegas Street Circuit',               class: 'Street Circuit' },
        { id: 'qatar',          name: 'Lusail International Circuit',           class: 'Grand Prix' },
        { id: 'yas_marina',      name: 'Yas Marina Circuit',                    class: 'Street Circuit' },
        { id: 'nurburgring_f1',  name: 'Nürburgring',                           class: 'Grand Prix' },
    ],

    // ── ASSETTO CORSA ──────────────────────────────────────────────────────
    ac: [
        { id: 'spa_ac',          name: 'Circuit de Spa-Francorchamps',             class: 'Grand Prix' },
        { id: 'monza_ac',         name: 'Autodromo Nazionale Monza',                class: 'Grand Prix' },
        { id: 'nurburgring_ac',  name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'silverstone_ac',  name: 'Silverstone Circuit',                     class: 'Grand Prix' },
        { id: 'barcelona_ac',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'imola_ac',         name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'misano_ac',       name: 'Misano World Circuit Marco Simoncelli',   class: 'Grand Prix' },
        { id: 'paul_ricard_ac',  name: 'Circuit Paul Ricard',                    class: 'Grand Prix' },
        { id: 'hockenheim_ac',   name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'zandvoort_ac',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'hungaroring_ac',  name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'oreal',           name: 'Circuit de Lédenon',                      class: 'Grand Prix' },
        { id: 'vallelunga_ac',   name: 'Autodromo di Vallelunga',               class: 'Grand Prix' },
        { id: 'magione',         name: 'Autodromo dell Umbria',                  class: 'Grand Prix' },
        { id: 'mugello',         name: 'Mugello Circuit',                       class: 'Grand Prix' },
        { id: 'brands_hatch_ac', name: 'Brands Hatch Circuit',                  class: 'Grand Prix' },
    ],

    // ── FORZA MOTORSPORT 2023 ───────────────────────────────────────────────
    forza: [
        { id: 'hockenheim_f',    name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'nurburgring_f',  name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'suzuka_f',        name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'silverstone_f',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'monza_f',         name: 'Autodromo Nazionale Monza',             class: 'Grand Prix' },
        { id: 'barcelona_f',     name: 'Circuit de Barcelona-Catalunya',         class: 'Grand Prix' },
        { id: 'mount_panorama_f', name: 'Mount Panorama Circuit',                 class: 'Grand Prix' },
        { id: 'lagunaseca_f',   name: 'WeatherTech Raceway Laguna Seca',       class: 'Grand Prix' },
        { id: 'indianapolis_f',  name: 'Indianapolis Motor Speedway',            class: 'Road Course' },
        { id: 'daytona_f',       name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'sebring_f',       name: 'Sebring International Raceway',        class: 'Road Course' },
        { id: 'road_america_f',  name: 'Road America',                         class: 'Road Course' },
        { id: 'tsukuba',          name: 'Tsukuba Circuit',                      class: 'Road Course' },
        { id: 'eagle_f',         name: 'Eagle Mountain',                        class: 'Road Course' },
        { id: 'vineyard_f',      name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'homestead_f',    name: 'Homestead-Miami Speedway',              class: 'Oval' },
    ],

    // ── rFactor 2 ───────────────────────────────────────────────────────────
    rf2: [
        { id: 'silverstone_rf2',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'spa_rf2',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_rf2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_rf2',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'barcelona_rf2',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'hungaroring_rf2',  name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'zandvoort_rf2',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'imola_rf2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'indianapolis_rf2', name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'orlando_rf2',      name: 'Orlando Speedworld',                    class: 'Road Course' },
    ],

    // ── AUTOMOBILISTA 2 ─────────────────────────────────────────────────────
    ams2: [
        { id: 'silverstone_ams2', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'spa_ams2',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_ams2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_ams2', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'barcelona_ams2',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'hungaroring_ams2', name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'zandvoort_ams2',   name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'imola_ams2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'misano_ams2',      name: 'Misano World Circuit Marco Simoncelli',   class: 'Grand Prix' },
        { id: 'mugello_ams2',     name: 'Mugello Circuit',                       class: 'Grand Prix' },
        { id: 'vallelunga_ams2',  name: 'Autodromo di Vallelunga',               class: 'Grand Prix' },
        { id: 'indianapolis_ams2', name: 'Indianapolis Motor Speedway',             class: 'Road Course' },
        { id: 'orlando_ams2',     name: 'Orlando Speedworld',                    class: 'Road Course' },
        { id: 'road_america_ams2', name: 'Road America',                         class: 'Road Course' },
        { id: 'watkins_glen_ams2', name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'jerez_ams2',        name: 'Circuito de Jerez',                     class: 'Grand Prix' },
        { id: 'estoril_ams2',     name: 'Circuito do Estoril',                   class: 'Grand Prix' },
    ],

    // ── LE MANS ULTIMATE ───────────────────────────────────────────────────
    lmu: [
        { id: 'le_mans_lmu',      name: 'Circuit de la Sarthe',                  class: 'Endurance' },
        { id: 'silverstone_lmu',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'nurburgring_lmu', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'spa_lmu',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_lmu',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'barcelona_lmu',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
    ],

    // ── RICHARD BURNS RALLY ─────────────────────────────────────────────────
    rbr: [
        { id: 'rbr_cyprus',      name: 'Cyprus',                                class: 'Rally' },
        { id: 'rbr_england',     name: 'England',                               class: 'Rally' },
        { id: 'rbr_greece',      name: 'Greece',                               class: 'Rally' },
        { id: 'rbr_japan',       name: 'Japan',                                 class: 'Rally' },
        { id: 'rbr_kenya',       name: 'Kenya',                                class: 'Rally' },
        { id: 'rbr_new_zealand', name: 'New Zealand',                          class: 'Rally' },
        { id: 'rbr_peru',        name: 'Peru',                                  class: 'Rally' },
        { id: 'rbr_ireland',     name: 'Ireland',                               class: 'Rally' },
    ],

    // ── DIRT RALLY 2.0 ─────────────────────────────────────────────────────
    dr2: [
        // RALLY LOCATIONS (26 locations with 169 stages)
        // European Classics
        { id: 'dr2_monte_carlo', name: 'Monte Carlo',                           class: 'European' },
        { id: 'dr2_sweden_rally', name: 'Sweden Rally',                          class: 'European' },
        { id: 'dr2_finland_rally', name: 'Finland Rally',                        class: 'European' },
        { id: 'dr2_germany_rally', name: 'Germany Rally (Rallye Deutschland)',   class: 'European' },
        { id: 'dr2_italy_rally', name: 'Italy Rally (Rally d\'Italia Sardegna)', class: 'European' },
        { id: 'dr2_spain_rally', name: 'Spain Rally (Rally RACC)',               class: 'European' },
        { id: 'dr2_wales_rally', name: 'Wales Rally GB',                         class: 'European' },
        { id: 'dr2_scotland_rally', name: 'Scotland Rally (Colin McRae)',        class: 'European' },
        { id: 'dr2_greece_rally', name: 'Greece Rally (Acropolis)',              class: 'European' },
        { id: 'dr2_portugal_rally', name: 'Portugal Rally',                      class: 'European' },
        { id: 'dr2_poland_rally', name: 'Poland Rally',                          class: 'European' },

        // Worldwide Locations
        { id: 'dr2_australia_rally', name: 'Australia Rally',                    class: 'Worldwide' },
        { id: 'dr2_argentina_rally', name: 'Argentina Rally',                    class: 'Worldwide' },
        { id: 'dr2_new_zealand_rally', name: 'New Zealand Rally',                class: 'Worldwide' },
        { id: 'dr2_japan_rally', name: 'Japan Rally',                            class: 'Worldwide' },
        { id: 'dr2_usa_rally', name: 'USA Rally',                                class: 'Worldwide' },
        { id: 'dr2_kenya_rally', name: 'Kenya Safari Rally',                     class: 'Worldwide' },
        { id: 'dr2_china_rally', name: 'China Rally',                            class: 'Worldwide' },
        { id: 'dr2_mexico_rally', name: 'Mexico Rally',                          class: 'Worldwide' },
        { id: 'dr2_thailand_rally', name: 'Thailand Rally',                      class: 'Worldwide' },
        { id: 'dr2_turkey_rally', name: 'Turkey Rally',                          class: 'Worldwide' },

        // Rallycross Locations (8 World RX locations)
        { id: 'dr2_1xrx_höljes', name: 'World RX - Höljes (Sweden)',             class: 'Rallycross' },
        { id: 'dr2_wrx_lohéac', name: 'World RX - Lohéac (France)',              class: 'Rallycross' },
        { id: 'dr2_wrx_lydden', name: 'World RX - Lydden Hill (UK)',            class: 'Rallycross' },
        { id: 'dr2_wrx_buxtedo', name: 'World RX - Buxtehude (Germany)',         class: 'Rallycross' },
    ],

    // ── EA SPORTS WRC ─────────────────────────────────────────────────────
    // 19 WRC Rally Locations
    wrc: [
        // Classic European Rounds
        { id: 'wrc_monte_carlo', name: 'Monte-Carlo Rally',                      class: 'European' },
        { id: 'wrc_rally_sweden', name: 'Rally Sweden',                          class: 'European' },
        { id: 'wrc_rally_estonia', name: 'Estonia Rally (Secto)',                class: 'Baltic' },
        { id: 'wrc_rally_finland', name: 'Arctic Rally Finland',                 class: 'European' },
        { id: 'wrc_acropolis_rally', name: 'Acropolis Rally Greece',             class: 'European' },
        { id: 'wrc_rally_italy', name: 'Rally Italia Sardegna',                  class: 'European' },
        { id: 'wrc_rally_españa', name: 'Rally RACC Spain (Catalonia)',          class: 'European' },
        { id: 'wrc_rally_france', name: 'Rally France Alsace',                   class: 'European' },
        { id: 'wrc_rally_belgium', name: 'Rally Belgium',                        class: 'European' },
        { id: 'wrc_rally_germany', name: 'Rallye Deutschland',                   class: 'European' },
        { id: 'wrc_wales_rally', name: 'Wales Rally GB',                         class: 'European' },

        // International Rounds
        { id: 'wrc_safari_rally_kenya', name: 'Kenya Safari Rally',              class: 'African' },
        { id: 'wrc_rally_chile', name: 'Rally Chile',                            class: 'South_American' },
        { id: 'wrc_rally_argentina', name: 'Rally Argentina',                    class: 'South_American' },
        { id: 'wrc_rally_japan', name: 'Rally Japan (Hokkaido)',                 class: 'Asian' },
        { id: 'wrc_rally_new_zealand', name: 'Rally New Zealand',                class: 'Oceania' },
        { id: 'wrc_rally_australia', name: 'Rally Australia',                    class: 'Oceania' },
        { id: 'wrc_rally_thailand', name: 'Rally Thailand',                      class: 'Asian' },
        { id: 'wrc_rally_mexico', name: 'Rally Mexico',                          class: 'North_American' },
    ],

    // ── RACEROOM ─────────────────────────────────────────────────────────────
    rrre: [
        { id: 'spa_rrre',        name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_rrre',       name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_rrre', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'silverstone_rrre', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona_rrre',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'zandvoort_rrre',   name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'hungaroring_rrre', name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'indianapolis_rrre', name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'daytona_rrre',     name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'watkins_glen_rrre', name: 'Watkins Glen International',            class: 'Road Course' },
    ],

    // ── PROJECT CARS 2 ──────────────────────────────────────────────────────
    pc2: [
        { id: 'spa_pc2',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_pc2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_pc2', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'silverstone_pc2', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona_pc2',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'imola_pc2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'suzuka_pc2',       name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'mount_panorama_pc2', name: 'Mount Panorama Circuit',                 class: 'Road Course' },
        { id: 'lagunaseca_pc2', name: 'WeatherTech Raceway Laguna Seca',       class: 'Road Course' },
        { id: 'indianapolis_pc2', name: 'Indianapolis Motor Speedway',            class: 'Road Course' },
        { id: 'daytona_pc2',      name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'sebring_pc2',      name: 'Sebring International Raceway',        class: 'Road Course' },
        { id: 'road_america_pc2', name: 'Road America',                         class: 'Road Course' },
        { id: 'watkins_glen_pc2', name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'hockenheim_pc2',  name: 'Hockenheimring Baden-Württemberg',     class: 'Grand Prix' },
    ],

    // ── NASCAR 21 ────────────────────────────────────────────────────────────
    nascar: [
        { id: 'daytona_nascar',   name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'phoenix_nascar',   name: 'Phoenix Raceway',                       class: 'Oval' },
        { id: 'lasvegas_nascar',  name: 'Las Vegas Motor Speedway',               class: 'Oval' },
        { id: 'atlanta_nascar',   name: 'Atlanta Motor Speedway',                 class: 'Oval' },
        { id: 'texas_nascar',     name: 'Texas Motor Speedway',                   class: 'Oval' },
        { id: 'talladega_nascar', name: 'Talladega Superspeedway',               class: 'Oval' },
        { id: 'charlotte_nascar', name: 'Charlotte Motor Speedway',              class: 'Oval' },
        { id: 'richmond_nascar',  name: 'Richmond Raceway',                      class: 'Oval' },
        { id: 'dover_nascar',     name: 'Dover International Speedway',           class: 'Oval' },
        { id: 'bristol_nascar',   name: 'Bristol Motor Speedway',               class: 'Oval' },
        { id: 'nashville_nascar', name: 'Nashville Superspeedway',               class: 'Oval' },
        { id: 'indianapolis_nascar', name: 'Indianapolis Motor Speedway',        class: 'Road Course' },
        { id: 'miami_nascar',     name: 'Homestead-Miami Speedway',               class: 'Oval' },
        { id: 'kansas_nascar',   name: 'Kansas Speedway',                       class: 'Oval' },
        { id: 'sonoma_nascar',   name: 'Sonoma Raceway',                       class: 'Road Course' },
    ],

    // ── KARTRRAFT ────────────────────────────────────────────────────────────
    kart: [
        { id: 'kart_bh',         name: 'Bahrain International KartCircuit',       class: 'Kart' },
        { id: 'kart_silverstone', name: 'Silverstone Circuit',                  class: 'Kart' },
        { id: 'kart_barcelona',   name: 'Circuit de Barcelona-Catalunya',       class: 'Kart' },
        { id: 'kart_suzuka',      name: 'Suzuka Circuit',                       class: 'Kart' },
        { id: 'kart_chengdu',     name: 'Chengdu TIC Circuit',                  class: 'Kart' },
        { id: 'kart_warner',     name: 'Warner Bros. Ranch',                   class: 'Kart' },
    ],

    // ── RENNSPORT ────────────────────────────────────────────────────────────
    rennsport: [
        { id: 'rs_spa',           name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'rs_monza',         name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'rs_nurburgring',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'rs_silverstone',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'rs_barcelona',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'rs_mount_panorama', name: 'Mount Panorama Circuit',                 class: 'Road Course' },
        { id: 'rs_lagunaseca',  name: 'WeatherTech Raceway Laguna Seca',        class: 'Road Course' },
    ],

    // ── CIRCUIT SUPERSTARS ──────────────────────────────────────────────────
    circuit: [
        { id: 'cs_silverstone',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'cs_spa',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'cs_monza',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'cs_nurburgring',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'cs_barcelona',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'cs_imola',         name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'cs_hockenheim',   name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'cs_zandvoort',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'cs_lago',         name: 'Lago Maggiore',                         class: 'Grand Prix' },
        { id: 'cs_sachsenring',  name: 'Sachsenring',                          class: 'Grand Prix' },
        { id: 'cs_zolder',        name: 'Circuit Zolder',                       class: 'Grand Prix' },
        { id: 'cs_oultonpark',   name: 'Oulton Park Circuit',                  class: 'Grand Prix' },
        { id: 'cs_snetterton',   name: 'Snetterton Motor Racing Circuit',       class: 'Grand Prix' },
        { id: 'cs_donington',    name: 'Donington Park Racing Circuit',          class: 'Grand Prix' },
    ],

    // ── LIVE FOR SPEED ───────────────────────────────────────────────────────
    lfs: [
        { id: 'lfs_blackwood',   name: 'Blackwood Circuit',                     class: 'Circuit' },
        { id: 'lfs_autocross',  name: 'Autocross Venue',                     class: 'Circuit' },
        { id: 'lfs_ferris',      name: 'Ferris Field',                       class: 'Circuit' },
        { id: 'lfs_weave',       name: 'Weave Map',                          class: 'Circuit' },
        { id: 'lfs_kairo',       name: 'Kairo Raceway',                     class: 'Circuit' },
        { id: 'lfs_southcity',  name: 'South City Classic',                 class: 'Circuit' },
        { id: 'lfs_surfers',    name: 'Surf City',                        class: 'Circuit' },
        { id: 'lfs_bally',       name: 'Bally on Map',                     class: 'Circuit' },
    ],

    // ── GRAN TURISMO SPORT ───────────────────────────────────────────────────
    gts: [
        { id: 'gts_bluewaters',  name: 'Bluewaters Bay',                        class: 'Road Track' },
        { id: 'gts_sardegna',   name: 'Sardegna - Road Track',                  class: 'Road Track' },
        { id: 'gts_tokyo',      name: 'Tokyo Expressway',                      class: 'Road Track' },
        { id: 'gts_suzuka_gts', name: 'Suzuka Circuit',                        class: 'World Circuits' },
        { id: 'gts_nurburgring', name: 'Nürburgring',                          class: 'World Circuits' },
        { id: 'gts_laguna_seca', name: 'WeatherTech Raceway Laguna Seca',      class: 'World Circuits' },
        { id: 'gts_willow',     name: 'Willow Springs',                        class: 'Road Track' },
        { id: 'gts_fuji',        name: 'Fuji Speedway',                        class: 'World Circuits' },
        { id: 'gts_trial',      name: 'Trial Mountain Circuit',                class: 'World Circuits' },
        { id: 'gts_groningen',   name: 'Autodromo di Vallelunga',               class: 'World Circuits' },
    ],

};
