// ─────────────────────────────────────────────────────────────────────────────
// CIRCUITS BY GAME
// Fuente: listados oficiales de cada juego + community wiki
// Formato: { id, name, class } — class = categoría de circuito para agrupar
// ─────────────────────────────────────────────────────────────────────────────

export const GAME_CIRCUITS = {

    // ── ASSETTO CORSA COMPETIZIONE ─────────────────────────────────────────
    acc: [
        { id: 'spa',              name: 'Circuit de Spa-Francorchamps',             class: 'Grand Prix' },
        { id: 'monza',            name: 'Autodromo Nazionale Monza',                class: 'Grand Prix' },
        { id: 'nurburgring',      name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'silverstone',      name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona',        name: 'Circuit de Barcelona-Catalunya',         class: 'Grand Prix' },
        { id: 'hungaroring',      name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'paul_ricard',      name: 'Circuit Paul Ricard',                    class: 'Grand Prix' },
        { id: 'zandvoort',       name: 'Circuit Zandvoort',                      class: 'Grand Prix' },
        { id: 'misano',           name: 'Misano World Circuit Marco Simoncelli',  class: 'Grand Prix' },
        { id: 'imola',            name: 'Autodromo Internazionale Enzo e Dino Ferrari', class: 'Grand Prix' },
        { id: 'brandshatch',      name: 'Brands Hatch Circuit',                  class: 'Grand Prix' },
        { id: 'donington',        name: 'Donington Park Racing Circuit',          class: 'Grand Prix' },
        { id: 'zolder',           name: 'Circuit Zolder',                         class: 'Grand Prix' },
        { id: 'lagunaseca',       name: 'WeatherTech Raceway Laguna Seca',      class: 'Grand Prix' },
        { id: 'sebring',          name: 'Sebring International Raceway',           class: 'Grand Prix' },
        { id: 'suzuka',           name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'bathurst',         name: 'Mount Panorama Circuit',                  class: 'Grand Prix' },
        { id: 'kyalami',         name: 'Kyalami Grand Prix Circuit',              class: 'Grand Prix' },
        { id: 'indianapolis',     name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'hockenheim',      name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'estoril',          name: 'Circuito do Estoril',                   class: 'Grand Prix' },
        { id: 'watkins_glen',     name: 'Watkins Glen International',           class: 'Grand Prix' },
        { id: 'zhuhai',          name: 'Zhuhai International Circuit',           class: 'Grand Prix' },
        { id: 'dubai',           name: 'Dubai Autodrome',                       class: 'Grand Prix' },
        { id: 'snetterton',       name: 'Snetterton Motor Racing Circuit',       class: 'Grand Prix' },
        { id: 'oultonpark',       name: 'Oulton Park Circuit',                   class: 'Grand Prix' },
        { id: 'mosport',          name: 'Canadian Tire Motorsport Park',          class: 'Grand Prix' },
        { id: 'salem',            name: 'Salem Circuit',                         class: 'Grand Prix' },
        { id: 'le_mans',          name: 'Circuit de la Sarthe',                  class: 'Endurance' },
        { id: 'gilles_villeneuve', name: 'Circuit Gilles Villeneuve',            class: 'Street Circuit' },
        { id: 'lasvegas',        name: 'Las Vegas Street Circuit',               class: 'Street Circuit' },
        { id: 'bahrain',          name: 'Bahrain International Circuit',         class: 'Grand Prix' },
    ],

    // ── iRacing ────────────────────────────────────────────────────────────
    iracing: [
        { id: 'silverstone_i',    name: 'Silverstone Circuit',                    class: 'Road Course' },
        { id: 'spa_i',           name: 'Circuit de Spa-Francorchamps',             class: 'Road Course' },
        { id: 'monza_i',          name: 'Autodromo Nazionale Monza',              class: 'Road Course' },
        { id: 'nurburgring_i',    name: 'Nürburgring',                          class: 'Road Course' },
        { id: 'barcelona_i',      name: 'Circuit de Barcelona-Catalunya',          class: 'Road Course' },
        { id: 'hungaroring_i',    name: 'Hungaroring',                          class: 'Road Course' },
        { id: 'zandvoort_i',     name: 'Circuit Zandvoort',                     class: 'Road Course' },
        { id: 'imola_i',          name: 'Autodromo Enzo e Dino Ferrari',          class: 'Road Course' },
        { id: 'indianapolis_i',   name: 'Indianapolis Motor Speedway',             class: 'Road Course' },
        { id: 'daytona',          name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'sebring_i',        name: 'Sebring International Raceway',          class: 'Road Course' },
        { id: 'road_america',     name: 'Road America',                          class: 'Road Course' },
        { id: 'watkins_glen_i',  name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'lagunaseca_i',    name: 'WeatherTech Raceway Laguna Seca',      class: 'Road Course' },
        { id: 'vir',              name: 'Virginia International Raceway',         class: 'Road Course' },
        { id: 'summit_point',    name: 'Summit Point Motorsports Park',         class: 'Road Course' },
        { id: 'orlando',         name: 'Orlando Speedworld',                    class: 'Road Course' },
        { id: 'test_track',      name: 'Charlotte Motor Speedway',               class: 'Oval' },
        { id: 'curitiba',        name: 'Autódromo Internacional de Curitiba',     class: 'Road Course' },
        { id: 'guia',            name: 'Autódromo do Estoril',                   class: 'Road Course' },
        { id: 'suzuka_i',        name: 'Suzuka Circuit',                        class: 'Road Course' },
        { id: 'mount_panorama_i', name: 'Mount Panorama Circuit',                 class: 'Road Course' },
        { id: 'brasilia',         name: 'Autódromo Internacional Nelson Piquet',  class: 'Road Course' },
        { id: 'salinas',          name: 'Autodromo di Vallelunga',              class: 'Road Course' },
        { id: 'buenos_aires',    name: 'Autódromo de Buenos Aires',             class: 'Street Circuit' },
        { id: 'hockenheim_i',    name: 'Hockenheimring Baden-Württemberg',     class: 'Road Course' },
        { id: 'misano_i',        name: 'Misano World Circuit Marco Simoncelli', class: 'Road Course' },
        { id: 'phoenix',         name: 'Phoenix International Raceway',          class: 'Oval' },
        { id: 'snetterton_i',    name: 'Snetterton Motor Racing Circuit',       class: 'Road Course' },
        { id: 'oultonpark_i',    name: 'Oulton Park Circuit',                  class: 'Road Course' },
    ],

    // ── GRAN TURISMO 7 ─────────────────────────────────────────────────────
    gt7: [
        { id: 'tokyo_expressway', name: 'Tokyo Expressway',                        class: 'Road Track' },
        { id: 'sardegna',        name: 'Sardegna - Road Track',                  class: 'Road Track' },
        { id: 'bluewaters_bay',   name: 'Bluewaters Bay',                         class: 'Road Track' },
        { id: 'alsace',          name: 'Alsace - Village',                       class: 'Road Track' },
        { id: 'bushido',         name: 'Blickwinkel',                           class: 'Road Track' },
        { id: 'deep_forest',     name: 'Deep Forest',                           class: 'Road Track' },
        { id: 'dragon_tail',     name: 'Dragon Trail',                          class: 'Road Track' },
        { id: 'willow_springs',  name: 'Willow Springs',                        class: 'Road Track' },
        { id: 'eagle_mountain',  name: 'Eagle Mountain',                        class: 'Road Track' },
        { id: 'fuji_speedway',   name: 'Fuji Speedway',                          class: 'Circuit Experience' },
        { id: 'autopolis',        name: 'Autopolis',                              class: 'Circuit Experience' },
        { id: 'suzuka_gt7',      name: 'Suzuka Circuit',                        class: 'Circuit Experience' },
        { id: 'nurburgring_gt7', name: 'Nürburgring',                           class: 'World Circuits' },
        { id: 'trial_mountain',   name: 'Trial Mountain Circuit',                class: 'Circuit Experience' },
        { id: 'laguna_seca_gt7', name: 'WeatherTech Raceway Laguna Seca',      class: 'World Circuits' },
        { id: 'homestead',       name: 'Homestead-Miami Speedway',               class: 'World Circuits' },
        { id: 'wellington',       name: 'Wellington Expressway',                  class: 'Street Circuit' },
        { id: 'sainte_croix',   name: 'Sainte-Croix',                          class: 'Road Track' },
        { id: 'gr1_cup',        name: 'Gr.1 Cup',                              class: 'Races' },
        { id: 'gr3_cup',        name: 'Gr.3 Cup',                              class: 'Races' },
    ],

    // ── F1 24 ──────────────────────────────────────────────────────────────
    f1_24: [
        { id: 'bahrain_f1',      name: 'Bahrain International Circuit',          class: 'Grand Prix' },
        { id: 'jeddah',          name: 'Jeddah Corniche Circuit',                 class: 'Street Circuit' },
        { id: 'albert_park',     name: 'Albert Park Grand Prix Circuit',         class: 'Street Circuit' },
        { id: 'suzuka_f1',      name: 'Suzuka International Racing Course',    class: 'Grand Prix' },
        { id: 'shanghai',        name: 'Shanghai International Circuit',          class: 'Grand Prix' },
        { id: 'miami',           name: 'Miami International Autodrome',          class: 'Street Circuit' },
        { id: 'catalunya_f1',   name: 'Circuit de Barcelona-Catalunya',           class: 'Grand Prix' },
        { id: 'monaco',          name: 'Circuit de Monaco',                      class: 'Street Circuit' },
        { id: 'gilles_villeneuve_f1', name: 'Circuit Gilles Villeneuve',          class: 'Street Circuit' },
        { id: 'silverstone_f1',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'red_bull_ring',   name: 'Red Bull Ring',                          class: 'Grand Prix' },
        { id: 'houston_street',  name: 'Heinz Field Street Circuit',             class: 'Street Circuit' },
        { id: 'zandvoort_f1',   name: 'Circuit Zandvoort',                      class: 'Grand Prix' },
        { id: 'monza_f1',        name: 'Autodromo Nazionale Monza',             class: 'Grand Prix' },
        { id: 'spa_f1',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'hungaroring_f1',  name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'zhou',           name: 'Zhuhai International Circuit',           class: 'Grand Prix' },
        { id: 'americas',        name: 'Circuit of the Americas',                class: 'Grand Prix' },
        { id: 'rodriguez',       name: 'Autodromo Hermanos Rodriguez',            class: 'Grand Prix' },
        { id: 'interlagos',      name: 'Autodromo Jose Carlos Pace',             class: 'Grand Prix' },
        { id: 'lasvegas_f1',    name: 'Las Vegas Street Circuit',               class: 'Street Circuit' },
        { id: 'qatar',          name: 'Lusail International Circuit',           class: 'Grand Prix' },
        { id: 'yas_marina',      name: 'Yas Marina Circuit',                    class: 'Street Circuit' },
        { id: 'nurburgring_f1',  name: 'Nürburgring',                           class: 'Grand Prix' },
    ],

    // ── ASSETTO CORSA ──────────────────────────────────────────────────────
    ac: [
        { id: 'spa_ac',          name: 'Circuit de Spa-Francorchamps',             class: 'Grand Prix' },
        { id: 'monza_ac',         name: 'Autodromo Nazionale Monza',                class: 'Grand Prix' },
        { id: 'nurburgring_ac',  name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'silverstone_ac',  name: 'Silverstone Circuit',                     class: 'Grand Prix' },
        { id: 'barcelona_ac',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'imola_ac',         name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'misano_ac',       name: 'Misano World Circuit Marco Simoncelli',   class: 'Grand Prix' },
        { id: 'paul_ricard_ac',  name: 'Circuit Paul Ricard',                    class: 'Grand Prix' },
        { id: 'hockenheim_ac',   name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'zandvoort_ac',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'hungaroring_ac',  name: 'Hungaroring',                           class: 'Grand Prix' },
        { id: 'oreal',           name: 'Circuit de Lédenon',                      class: 'Grand Prix' },
        { id: 'vallelunga_ac',   name: 'Autodromo di Vallelunga',               class: 'Grand Prix' },
        { id: 'magione',         name: 'Autodromo dell Umbria',                  class: 'Grand Prix' },
        { id: 'mugello',         name: 'Mugello Circuit',                       class: 'Grand Prix' },
        { id: 'brands_hatch_ac', name: 'Brands Hatch Circuit',                  class: 'Grand Prix' },
    ],

    // ── FORZA MOTORSPORT 2023 ───────────────────────────────────────────────
    forza: [
        { id: 'hockenheim_f',    name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'nurburgring_f',  name: 'Nürburgring',                           class: 'Grand Prix' },
        { id: 'suzuka_f',        name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'silverstone_f',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'monza_f',         name: 'Autodromo Nazionale Monza',             class: 'Grand Prix' },
        { id: 'barcelona_f',     name: 'Circuit de Barcelona-Catalunya',         class: 'Grand Prix' },
        { id: 'mount_panorama_f', name: 'Mount Panorama Circuit',                 class: 'Grand Prix' },
        { id: 'lagunaseca_f',   name: 'WeatherTech Raceway Laguna Seca',       class: 'Grand Prix' },
        { id: 'indianapolis_f',  name: 'Indianapolis Motor Speedway',            class: 'Road Course' },
        { id: 'daytona_f',       name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'sebring_f',       name: 'Sebring International Raceway',        class: 'Road Course' },
        { id: 'road_america_f',  name: 'Road America',                         class: 'Road Course' },
        { id: 'tsukuba',          name: 'Tsukuba Circuit',                      class: 'Road Course' },
        { id: 'eagle_f',         name: 'Eagle Mountain',                        class: 'Road Course' },
        { id: 'vineyard_f',      name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'homestead_f',    name: 'Homestead-Miami Speedway',              class: 'Oval' },
    ],

    // ── rFactor 2 ───────────────────────────────────────────────────────────
    rf2: [
        { id: 'silverstone_rf2',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'spa_rf2',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_rf2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_rf2',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'barcelona_rf2',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'hungaroring_rf2',  name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'zandvoort_rf2',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'imola_rf2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'indianapolis_rf2', name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'orlando_rf2',      name: 'Orlando Speedworld',                    class: 'Road Course' },
    ],

    // ── AUTOMOBILISTA 2 ─────────────────────────────────────────────────────
    ams2: [
        { id: 'silverstone_ams2', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'spa_ams2',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_ams2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_ams2', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'barcelona_ams2',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'hungaroring_ams2', name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'zandvoort_ams2',   name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'imola_ams2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'misano_ams2',      name: 'Misano World Circuit Marco Simoncelli',   class: 'Grand Prix' },
        { id: 'mugello_ams2',     name: 'Mugello Circuit',                       class: 'Grand Prix' },
        { id: 'vallelunga_ams2',  name: 'Autodromo di Vallelunga',               class: 'Grand Prix' },
        { id: 'indianapolis_ams2', name: 'Indianapolis Motor Speedway',             class: 'Road Course' },
        { id: 'orlando_ams2',     name: 'Orlando Speedworld',                    class: 'Road Course' },
        { id: 'road_america_ams2', name: 'Road America',                         class: 'Road Course' },
        { id: 'watkins_glen_ams2', name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'jerez_ams2',        name: 'Circuito de Jerez',                     class: 'Grand Prix' },
        { id: 'estoril_ams2',     name: 'Circuito do Estoril',                   class: 'Grand Prix' },
    ],

    // ── LE MANS ULTIMATE ───────────────────────────────────────────────────
    lmu: [
        { id: 'le_mans_lmu',      name: 'Circuit de la Sarthe',                  class: 'Endurance' },
        { id: 'silverstone_lmu',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'nurburgring_lmu', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'spa_lmu',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_lmu',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'barcelona_lmu',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
    ],

    // ── RICHARD BURNS RALLY ─────────────────────────────────────────────────
    rbr: [
        { id: 'rbr_cyprus',      name: 'Cyprus',                                class: 'Rally' },
        { id: 'rbr_england',     name: 'England',                               class: 'Rally' },
        { id: 'rbr_greece',      name: 'Greece',                               class: 'Rally' },
        { id: 'rbr_japan',       name: 'Japan',                                 class: 'Rally' },
        { id: 'rbr_kenya',       name: 'Kenya',                                class: 'Rally' },
        { id: 'rbr_new_zealand', name: 'New Zealand',                          class: 'Rally' },
        { id: 'rbr_peru',        name: 'Peru',                                  class: 'Rally' },
        { id: 'rbr_ireland',     name: 'Ireland',                               class: 'Rally' },
    ],

    // ── DIRT RALLY 2.0 ─────────────────────────────────────────────────────
    dr2: [
        { id: 'dr2_greece',      name: 'Greece',                               class: 'Rally' },
        { id: 'dr2_argentina',   name: 'Argentina',                           class: 'Rally' },
        { id: 'dr2_australia',   name: 'Australia',                           class: 'Rally' },
        { id: 'dr2_new_zealand', name: 'New Zealand',                        class: 'Rally' },
        { id: 'dr2_poland',       name: 'Poland',                             class: 'Rally' },
        { id: 'dr2_spain',        name: 'Spain',                              class: 'Rally' },
        { id: 'dr2_finland',      name: 'Finland',                            class: 'Rally' },
        { id: 'dr2_germany',      name: 'Germany',                            class: 'Rally' },
        { id: 'dr2_italy',       name: 'Italy',                              class: 'Rally' },
        { id: 'dr2_sweden',      name: 'Sweden',                             class: 'Rally' },
        { id: 'dr2_norway',      name: 'Norway',                             class: 'Rally' },
        { id: 'dr2_kenya',       name: 'Kenya',                              class: 'Rally' },
        { id: 'dr2_japan',       name: 'Japan',                               class: 'Rally' },
        { id: 'dr2_usa',         name: 'USA',                                class: 'Rally' },
    ],

    // ── EA SPORTS WRC ─────────────────────────────────────────────────────
    wrc: [
        { id: 'wrc_monaco',      name: 'Monte-Carlo',                         class: 'Rally' },
        { id: 'wrc_sweden',      name: 'Sweden',                             class: 'Rally' },
        { id: 'wrc_kenya',       name: 'Kenya',                              class: 'Rally' },
        { id: 'wrc_chile',       name: 'Chile',                              class: 'Rally' },
        { id: 'wrc_eth',        name: 'Ethiopia',                           class: 'Rally' },
        { id: 'wrc_italy',       name: 'Italy',                              class: 'Rally' },
        { id: 'wrc_estonia',    name: 'Estonia',                            class: 'Rally' },
        { id: 'wrc_finland',     name: 'Finland',                            class: 'Rally' },
        { id: 'wrc_greece',     name: 'Greece',                             class: 'Rally' },
        { id: 'wrc_japan',       name: 'Japan',                               class: 'Rally' },
        { id: 'wrc_central_europe', name: 'Central Europe',                   class: 'Rally' },
        { id: 'wrc_spain',       name: 'Spain',                              class: 'Rally' },
        { id: 'wrc_australia',   name: 'Australia',                         class: 'Rally' },
    ],

    // ── RACEROOM ─────────────────────────────────────────────────────────────
    rrre: [
        { id: 'spa_rrre',        name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_rrre',       name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_rrre', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'silverstone_rrre', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona_rrre',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'zandvoort_rrre',   name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'hungaroring_rrre', name: 'Hungaroring',                          class: 'Grand Prix' },
        { id: 'indianapolis_rrre', name: 'Indianapolis Motor Speedway',             class: 'Oval / Road' },
        { id: 'daytona_rrre',     name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'watkins_glen_rrre', name: 'Watkins Glen International',            class: 'Road Course' },
    ],

    // ── PROJECT CARS 2 ──────────────────────────────────────────────────────
    pc2: [
        { id: 'spa_pc2',         name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'monza_pc2',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'nurburgring_pc2', name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'silverstone_pc2', name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'barcelona_pc2',   name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'imola_pc2',        name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'suzuka_pc2',       name: 'Suzuka Circuit',                        class: 'Grand Prix' },
        { id: 'mount_panorama_pc2', name: 'Mount Panorama Circuit',                 class: 'Road Course' },
        { id: 'lagunaseca_pc2', name: 'WeatherTech Raceway Laguna Seca',       class: 'Road Course' },
        { id: 'indianapolis_pc2', name: 'Indianapolis Motor Speedway',            class: 'Road Course' },
        { id: 'daytona_pc2',      name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'sebring_pc2',      name: 'Sebring International Raceway',        class: 'Road Course' },
        { id: 'road_america_pc2', name: 'Road America',                         class: 'Road Course' },
        { id: 'watkins_glen_pc2', name: 'Watkins Glen International',            class: 'Road Course' },
        { id: 'hockenheim_pc2',  name: 'Hockenheimring Baden-Württemberg',     class: 'Grand Prix' },
    ],

    // ── NASCAR 21 ────────────────────────────────────────────────────────────
    nascar: [
        { id: 'daytona_nascar',   name: 'Daytona International Speedway',         class: 'Oval' },
        { id: 'phoenix_nascar',   name: 'Phoenix Raceway',                       class: 'Oval' },
        { id: 'lasvegas_nascar',  name: 'Las Vegas Motor Speedway',               class: 'Oval' },
        { id: 'atlanta_nascar',   name: 'Atlanta Motor Speedway',                 class: 'Oval' },
        { id: 'texas_nascar',     name: 'Texas Motor Speedway',                   class: 'Oval' },
        { id: 'talladega_nascar', name: 'Talladega Superspeedway',               class: 'Oval' },
        { id: 'charlotte_nascar', name: 'Charlotte Motor Speedway',              class: 'Oval' },
        { id: 'richmond_nascar',  name: 'Richmond Raceway',                      class: 'Oval' },
        { id: 'dover_nascar',     name: 'Dover International Speedway',           class: 'Oval' },
        { id: 'bristol_nascar',   name: 'Bristol Motor Speedway',               class: 'Oval' },
        { id: 'nashville_nascar', name: 'Nashville Superspeedway',               class: 'Oval' },
        { id: 'indianapolis_nascar', name: 'Indianapolis Motor Speedway',        class: 'Road Course' },
        { id: 'miami_nascar',     name: 'Homestead-Miami Speedway',               class: 'Oval' },
        { id: 'kansas_nascar',   name: 'Kansas Speedway',                       class: 'Oval' },
        { id: 'sonoma_nascar',   name: 'Sonoma Raceway',                       class: 'Road Course' },
    ],

    // ── KARTRRAFT ────────────────────────────────────────────────────────────
    kart: [
        { id: 'kart_bh',         name: 'Bahrain International KartCircuit',       class: 'Kart' },
        { id: 'kart_silverstone', name: 'Silverstone Circuit',                  class: 'Kart' },
        { id: 'kart_barcelona',   name: 'Circuit de Barcelona-Catalunya',       class: 'Kart' },
        { id: 'kart_suzuka',      name: 'Suzuka Circuit',                       class: 'Kart' },
        { id: 'kart_chengdu',     name: 'Chengdu TIC Circuit',                  class: 'Kart' },
        { id: 'kart_warner',     name: 'Warner Bros. Ranch',                   class: 'Kart' },
    ],

    // ── RENNSPORT ────────────────────────────────────────────────────────────
    rennsport: [
        { id: 'rs_spa',           name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'rs_monza',         name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'rs_nurburgring',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'rs_silverstone',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'rs_barcelona',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'rs_mount_panorama', name: 'Mount Panorama Circuit',                 class: 'Road Course' },
        { id: 'rs_lagunaseca',  name: 'WeatherTech Raceway Laguna Seca',        class: 'Road Course' },
    ],

    // ── CIRCUIT SUPERSTARS ──────────────────────────────────────────────────
    circuit: [
        { id: 'cs_silverstone',  name: 'Silverstone Circuit',                    class: 'Grand Prix' },
        { id: 'cs_spa',          name: 'Circuit de Spa-Francorchamps',            class: 'Grand Prix' },
        { id: 'cs_monza',        name: 'Autodromo Nazionale Monza',              class: 'Grand Prix' },
        { id: 'cs_nurburgring',  name: 'Nürburgring',                          class: 'Grand Prix' },
        { id: 'cs_barcelona',    name: 'Circuit de Barcelona-Catalunya',          class: 'Grand Prix' },
        { id: 'cs_imola',         name: 'Autodromo Enzo e Dino Ferrari',           class: 'Grand Prix' },
        { id: 'cs_hockenheim',   name: 'Hockenheimring Baden-Württemberg',      class: 'Grand Prix' },
        { id: 'cs_zandvoort',    name: 'Circuit Zandvoort',                     class: 'Grand Prix' },
        { id: 'cs_lago',         name: 'Lago Maggiore',                         class: 'Grand Prix' },
        { id: 'cs_sachsenring',  name: 'Sachsenring',                          class: 'Grand Prix' },
        { id: 'cs_zolder',        name: 'Circuit Zolder',                       class: 'Grand Prix' },
        { id: 'cs_oultonpark',   name: 'Oulton Park Circuit',                  class: 'Grand Prix' },
        { id: 'cs_snetterton',   name: 'Snetterton Motor Racing Circuit',       class: 'Grand Prix' },
        { id: 'cs_donington',    name: 'Donington Park Racing Circuit',          class: 'Grand Prix' },
    ],

    // ── LIVE FOR SPEED ───────────────────────────────────────────────────────
    lfs: [
        { id: 'lfs_blackwood',   name: 'Blackwood Circuit',                     class: 'Circuit' },
        { id: 'lfs_autocross',  name: 'Autocross Venue',                     class: 'Circuit' },
        { id: 'lfs_ferris',      name: 'Ferris Field',                       class: 'Circuit' },
        { id: 'lfs_weave',       name: 'Weave Map',                          class: 'Circuit' },
        { id: 'lfs_kairo',       name: 'Kairo Raceway',                     class: 'Circuit' },
        { id: 'lfs_southcity',  name: 'South City Classic',                 class: 'Circuit' },
        { id: 'lfs_surfers',    name: 'Surf City',                        class: 'Circuit' },
        { id: 'lfs_bally',       name: 'Bally on Map',                     class: 'Circuit' },
    ],

    // ── GRAN TURISMO SPORT ───────────────────────────────────────────────────
    gts: [
        { id: 'gts_bluewaters',  name: 'Bluewaters Bay',                        class: 'Road Track' },
        { id: 'gts_sardegna',   name: 'Sardegna - Road Track',                  class: 'Road Track' },
        { id: 'gts_tokyo',      name: 'Tokyo Expressway',                      class: 'Road Track' },
        { id: 'gts_suzuka_gts', name: 'Suzuka Circuit',                        class: 'World Circuits' },
        { id: 'gts_nurburgring', name: 'Nürburgring',                          class: 'World Circuits' },
        { id: 'gts_laguna_seca', name: 'WeatherTech Raceway Laguna Seca',      class: 'World Circuits' },
        { id: 'gts_willow',     name: 'Willow Springs',                        class: 'Road Track' },
        { id: 'gts_fuji',        name: 'Fuji Speedway',                        class: 'World Circuits' },
        { id: 'gts_trial',      name: 'Trial Mountain Circuit',                class: 'World Circuits' },
        { id: 'gts_groningen',   name: 'Autodromo di Vallelunga',               class: 'World Circuits' },
    ],

};
