// ─────────────────────────────────────────────────────────────────────────────
// GT7 CAR OVERRIDES — Gran Turismo 7
// Fuentes: GT7 wiki, community setup guides, in-game data.
// GT7 tiene classes muy diferentes (Gr.1, Gr.3, Gr.4, Gr.B, Formula, Street, Rally).
// Cada class tiene parâmetros únicos y rangos diferentes.
// ─────────────────────────────────────────────────────────────────────────────

const GT7_CAR_OVERRIDES = {

    // ── GR.1 — top class, resembles real GT1/Group C ──────────────────────
    'gr1_vgt': {
        name: 'Gr.1 - Vision GT',
        class: 'Gr.1',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 120, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 80, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 300, aeroStep: 1,
    },
    'gr1_918': {
        name: 'Gr.1 - Porsche 918 RSR',
        class: 'Gr.1',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 120, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 80, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 300, aeroStep: 1,
    },
    'gr1_gs': {
        name: 'Gr.1 - Mercedes-AMG GT',
        class: 'Gr.1',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 120, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 80, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 300, aeroStep: 1,
    },

    // ── GR.3 — GT3-style, lower downforce ─────────────────────────────────
    'gr3_supra': {
        name: 'Gr.3 - Toyota Supra GT500',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },
    'gr3_86': {
        name: 'Gr.3 - Toyota 86 GT',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },
    'gr3_nismo': {
        name: 'Gr.3 - Nissan GT-R Nismo',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },
    'gr3_amg': {
        name: 'Gr.3 - Mercedes-AMG GT',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },
    'gr3_bmwm4': {
        name: 'Gr.3 - BMW M4 GT3',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },
    'gr3_raser': {
        name: 'Gr.3 - Lexus RC F',
        class: 'Gr.3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 130, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 200, aeroStep: 1,
    },

    // ── GR.4 — production-based sports cars ─────────────────────────────────
    'gr4_megane': {
        name: 'Gr.4 - Renault Megane Trophy',
        class: 'Gr.4',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 70, heightFrontMax: 140, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 150, aeroStep: 1,
    },
    'gr4_a45': {
        name: 'Gr.4 - Mercedes-AMG A45',
        class: 'Gr.4',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 70, heightFrontMax: 140, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 150, aeroStep: 1,
    },
    'gr4_gtr': {
        name: 'Gr.4 - Nissan GT-R',
        class: 'Gr.4',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.1,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 70, heightFrontMax: 140, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 150, aeroStep: 1,
    },

    // ── GR.B — rally ───────────────────────────────────────────────────────
    'grb_quattro': {
        name: 'Gr.B - Audi Sport Quattro',
        class: 'Gr.B',
        tyrePressureMin: 24.0, tyrePressureMax: 32.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -4.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 65, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 180, heightFrontMax: 250, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
    'grb_evo': {
        name: 'Gr.B - Subaru WRX',
        class: 'Gr.B',
        tyrePressureMin: 24.0, tyrePressureMax: 32.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -4.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 65, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 180, heightFrontMax: 250, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },

    // ── FORMULA ─────────────────────────────────────────────────────────────
    'formula_s': {
        name: 'Formula Sport',
        class: 'Formula',
        tyrePressureMin: 19.0, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -4.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.40, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.50,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 30, heightFrontMax: 80, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 80, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 300, aeroStep: 1,
    },
    'formula_2': {
        name: 'Formula 2',
        class: 'Formula',
        tyrePressureMin: 19.0, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -4.0, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.40, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.50,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 30, heightFrontMax: 80, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 80, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 300, aeroStep: 1,
    },

    // ── STREET ─────────────────────────────────────────────────────────────
    'street_nsx': {
        name: 'Street - Honda NSX',
        class: 'Street',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -0.5, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 150, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
    'street_supra': {
        name: 'Street - Toyota GR Supra',
        class: 'Street',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -0.5, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 150, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
    'street_86': {
        name: 'Street - Toyota 86',
        class: 'Street',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -0.5, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 150, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
    'street_civic': {
        name: 'Street - Honda Civic Type R',
        class: 'Street',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -0.5, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 150, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
    'street_370z': {
        name: 'Street - Nissan 370Z',
        class: 'Street',
        tyrePressureMin: 28.0, tyrePressureMax: 35.0, tyrePressureStep: 0.1,
        camberFrontMin: -3.5, camberFrontMax: -0.5, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 60, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 150, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },

    // ── RALLY ──────────────────────────────────────────────────────────────
    'rally_gr': {
        name: 'Rally - Toyota GR Yaris',
        class: 'Rally',
        tyrePressureMin: 24.0, tyrePressureMax: 32.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -4.0, camberRearMax: -0.5,
        brakeBiasMin: 50, brakeBiasMax: 65, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 180, heightFrontMax: 250, heightStep: 1,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        extensionFMin: 1, extensionFMax: 10, extensionStep: 1,
        compressionFMin: 1, compressionFMax: 10, compressionStep: 1,
        lsdInitialMin: 5, lsdInitialMax: 60, lsdStep: 1,
        aeroFrontMin: 0, aeroFrontMax: 100, aeroStep: 1,
    },
};

export function getGT7CarOverride(carId) {
    return GT7_CAR_OVERRIDES[carId] || null;
}
