// ─────────────────────────────────────────────────────────────────────────────
// IRACING CAR OVERRIDES
// Fuentes: iRacing wiki, setup guides, community spreadsheets.
// iRacing tiene classes muy diferentes (GT3, GT4, Formula, NASCAR, LMDh, LMP2).
// Cada class tiene parâmetros y rangos únicos.
// ─────────────────────────────────────────────────────────────────────────────

const IRACING_CAR_OVERRIDES = {

    // ── GT3 ────────────────────────────────────────────────────────────────
    'gt3_ferrari_296': {
        name: 'Ferrari 296 GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_porsche_911': {
        name: 'Porsche 911 GT3 R',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_bmw_m4': {
        name: 'BMW M4 GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_mercedes': {
        name: 'Mercedes-AMG GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_audi_r8': {
        name: 'Audi R8 LMS GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_mclaren_720s': {
        name: 'McLaren 720S GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'gt3_nissan_gt_r': {
        name: 'Nissan GT-R Nismo GT3',
        class: 'GT3',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },

    // ── FORMULA ────────────────────────────────────────────────────────────
    'formula_f3': {
        name: 'Dallara F3',
        class: 'Formula',
        tyrePressureMin: 19.0, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -4.5, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.40, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.50,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        heightFrontMin: 30, heightFrontMax: 80, heightStep: 1,
        heightRearMin: 35, heightRearMax: 90, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'formula_sf23': {
        name: 'Super Formula SF23',
        class: 'Formula',
        tyrePressureMin: 19.0, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -4.5, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.40, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.50,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        heightFrontMin: 30, heightFrontMax: 80, heightStep: 1,
        heightRearMin: 35, heightRearMax: 90, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },
    'formula_ir01': {
        name: 'IndyCar IR-01',
        class: 'Formula',
        tyrePressureMin: 19.0, tyrePressureMax: 25.0, tyrePressureStep: 0.1,
        camberFrontMin: -5.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -4.5, camberRearMax: -1.0,
        toeFrontMin: 0.00, toeFrontMax: 0.40, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.50,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        heightFrontMin: 30, heightFrontMax: 80, heightStep: 1,
        heightRearMin: 35, heightRearMax: 90, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
        tyreBlanketTempMin: 50, tyreBlanketTempMax: 110, tyreBlanketStep: 5,
    },

    // ── NASCAR ─────────────────────────────────────────────────────────────
    'nascar_c7': {
        name: 'NASCAR Chevrolet C7.R',
        class: 'NASCAR',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.40,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 140, heightStep: 1,
        heightRearMin: 85, heightRearMax: 150, heightStep: 1,
        wedgeMin: 0, wedgeMax: 5, wedgeStep: 0.1,
    },
    'nascar_nextgen': {
        name: 'NASCAR Next Gen Chevrolet',
        class: 'NASCAR',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.40,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 140, heightStep: 1,
        heightRearMin: 85, heightRearMax: 150, heightStep: 1,
        wedgeMin: 0, wedgeMax: 5, wedgeStep: 0.1,
    },
    'nascar_mustang': {
        name: 'NASCAR Ford Mustang',
        class: 'NASCAR',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.40,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 140, heightStep: 1,
        heightRearMin: 85, heightRearMax: 150, heightStep: 1,
        wedgeMin: 0, wedgeMax: 5, wedgeStep: 0.1,
    },
    'nascar_camaro': {
        name: 'NASCAR Chevrolet Camaro',
        class: 'NASCAR',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.0, camberStep: 0.1,
        camberRearMin:  -3.0, camberRearMax: -0.5,
        toeFrontMin: 0.00, toeFrontMax: 0.30, toeStep: 0.01,
        toeRearMin:  0.05, toeRearMax:  0.40,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 80, heightFrontMax: 140, heightStep: 1,
        heightRearMin: 85, heightRearMax: 150, heightStep: 1,
        wedgeMin: 0, wedgeMax: 5, wedgeStep: 0.1,
    },

    // ── LMDh ──────────────────────────────────────────────────────────────
    'lmdh_cadillac': {
        name: 'Cadillac V-Series.R',
        class: 'LMDh',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },
    'lmdh_bmw': {
        name: 'BMW M Hybrid V8',
        class: 'LMDh',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },
    'lmdh_porsche': {
        name: 'Porsche 963',
        class: 'LMDh',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },

    // ── LMP2 ──────────────────────────────────────────────────────────────
    'lmp2_oreca': {
        name: 'Oreca 07',
        class: 'LMP2',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },
    'lmp2_duo': {
        name: 'Dallara P217',
        class: 'LMP2',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 14, arbStep: 1,
        arbRearMin: 1, arbRearMax: 14, arbStep: 1,
        brakeBiasMin: 46.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 50, heightFrontMax: 100, heightStep: 1,
        heightRearMin: 55, heightRearMax: 110, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },

    // ── GT4 ───────────────────────────────────────────────────────────────
    'gt4_aston': {
        name: 'Aston Martin Vantage GT4',
        class: 'GT4',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        arbRearMin: 1, arbRearMax: 10, arbStep: 1,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 120, heightStep: 1,
        heightRearMin: 65, heightRearMax: 130, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },
    'gt4_mclaren': {
        name: 'McLaren 570S GT4',
        class: 'GT4',
        tyrePressureMin: 26.0, tyrePressureMax: 33.0, tyrePressureStep: 0.1,
        camberFrontMin: -4.0, camberFrontMax: -1.5, camberStep: 0.05,
        camberRearMin:  -3.5, camberRearMax: -1.0,
        toeFrontMin: -0.30, toeFrontMax: 0.20, toeStep: 0.01,
        toeRearMin:   0.00, toeRearMax:  0.40,
        arbFrontMin: 1, arbFrontMax: 10, arbStep: 1,
        arbRearMin: 1, arbRearMax: 10, arbStep: 1,
        brakeBiasMin: 50.0, brakeBiasMax: 60.0, brakeBiasStep: 0.1,
        brakePowerMin: 80, brakePowerMax: 100, brakePowerStep: 1,
        heightFrontMin: 60, heightFrontMax: 120, heightStep: 1,
        heightRearMin: 65, heightRearMax: 130, heightStep: 1,
        diffPreloadMin: 20, diffPreloadMax: 200, diffPreloadStep: 5,
    },
};

export function getIRacingCarOverride(carId) {
    return IRACING_CAR_OVERRIDES[carId] || null;
}
